set -g status-style bg=default,fg=white

# status bar
set -g window-status-format "[#I][#W]"
set -g window-status-current-format "#[fg=blue][#I][#W]"

set -g status-left "[ "
set -g status-right " ]"

# borders
set -g pane-border-style fg=white
set -g pane-active-border-style "fg=white"

tmux set -g pane-border-lines double