set -g mouse on

# Set base window to 1
set -g base-index 1
setw -g pane-base-index 1
set-option -g renumber-windows on

# Enable 256 bit colors
set -g default-terminal "tmux-256color"
set -ga terminal-overrides ",*:Tc"


# Style
source "$XDG_CONFIG_HOME/tmux/style.conf"
